rly_file = "Ipswich.rly"
ttb_files = [ "Ipswich 11-09-24.ttb",]
ssn_files = [ "Ipswich Initial Session.ssn",]
img_files = [ "Ipswich.bmp",]
doc_files = [ "Ipswich.md",]
release_date = "2024-09-14"
version = "1.0.0"
country_code = "GB"
factual = true
description = ""
year = 2024
display_name = "Ipswich"
name = "Ipswich"
signal_position = "left"
author = "Oxalin1"
contributors = []
