author = 'Oxalin'
country_code = 'GB'
description = "Great Eastern Main Line from Ipswich to Diss, and Felixstowe branch."
display_name = 'Ipswich'
doc_files = [ 'Ipswich.md' ]
factual = true
img_files = [ 'Ipswich.bmp' ]
name = 'Ipswich'
release_date = '2024-09-14'
rly_file = 'Ipswich.rly'
ssn_files = [ 'Ipswich Initial Session.ssn']
ttb_files = [ 'Ipswich 11-09-24.ttb' ]
year = 2024
signal_position = "left"
version = '1.0.0'
